name: generate-ical-feed

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out reposority
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # ensure full history so we can push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate iCal file
        run: python generate_ics.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: public
          publish_dir: docs
          commit_message: chore: update fixtures [skip ci]
