name: Generate iCal feed

on:
  schedule:
    # every hour on the hour; adjust as needed
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate iCal file
        run: python generate_ics.py

      - name: Commit & push fixtures.ics
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "chore: update fixtures.ics [skip ci]"
          add: "docs/fixtures.ics"
