name: send-availability-checker

on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  email:
    runs-on: ubuntu-latest
    env:
      SMTP_HOST:     ${{ secrets.SMTP_HOST }}
      SMTP_PORT:     ${{ secrets.SMTP_PORT }}
      SMTP_USER:     ${{ secrets.SMTP_USER }}
      SMTP_PASS:     ${{ secrets.SMTP_PASS }}
      EMAIL_SENDER:  ${{ secrets.EMAIL_SENDER }}
      RECIPIENTS:    ${{ secrets.RECIPIENTS }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 ics
      - name: Send reminders
        run: python email_reminder.py
